// This file was generated by stencil.py

#include <PNSystem.h>

void set_system_row(PNSystem::VoxelSystem& sys,
					PNSystem::Fields& fields)
{
	V2i vi = sys.getVoxel();
	V2d vd = sys.getVoxel().cast<double>();
	V2d h_inv( 1.0/(1*sys.getVoxelSize()[0]), 1.0/(1*sys.getVoxelSize()[1]) );

}

#define REGISTER_STENCIL(name, order) \
	static struct name ##_{ \
		name ##_() { \
			PNSystem::registerStencil(#name, PNSystem::Stencil( order, name )); \
		} \
	}name ##__;


REGISTER_STENCIL( set_system_row, 1 )
