// This file was generated by stencil.py

#include <PNSystem.h>

void stencil_fopn_p4_sg(PNSystem::Stencil::Context& ctx)
{
	V3i vi = ctx.getVoxelCoord();
	V3d vd = vi.cast<double>();
	const Domain& domain = ctx.getDomain();
	const PNVolume& problem = ctx.getProblem();
	V3d h_inv( 1.0/(1*domain.getVoxelSize()[0]), 1.0/(1*domain.getVoxelSize()[1]), 1.0/(1*domain.getVoxelSize()[2]) );
	int color_channel = 0;

	Eigen::Matrix<std::complex<double>, 25, 25> S;
	S.coeffRef(0, 0) = std::complex<double>(1.0, 0.0);
	S.coeffRef(1, 1) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(1, 3) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(2, 1) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(2, 3) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(3, 2) = std::complex<double>(1.0, 0.0);
	S.coeffRef(4, 4) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(4, 8) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(5, 4) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(5, 8) = std::complex<double>(0.0, 0.7071067811865475);
	S.coeffRef(6, 5) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(6, 7) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(7, 5) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(7, 7) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(8, 6) = std::complex<double>(1.0, 0.0);
	S.coeffRef(9, 9) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(9, 15) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(10, 9) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(10, 15) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(11, 10) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(11, 14) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(12, 10) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(12, 14) = std::complex<double>(0.0, 0.7071067811865475);
	S.coeffRef(13, 11) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(13, 13) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(14, 11) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(14, 13) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(15, 12) = std::complex<double>(1.0, 0.0);
	S.coeffRef(16, 16) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(16, 24) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(17, 16) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(17, 24) = std::complex<double>(0.0, 0.7071067811865475);
	S.coeffRef(18, 17) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(18, 23) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(19, 17) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(19, 23) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(20, 18) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(20, 22) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(21, 18) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(21, 22) = std::complex<double>(0.0, 0.7071067811865475);
	S.coeffRef(22, 19) = std::complex<double>(0.7071067811865475, 0.0);
	S.coeffRef(22, 21) = std::complex<double>(-0.7071067811865475, 0.0);
	S.coeffRef(23, 19) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(23, 21) = std::complex<double>(-0.0, -0.7071067811865475);
	S.coeffRef(24, 20) = std::complex<double>(1.0, 0.0);
	Eigen::Matrix<std::complex<double>, 25, 25> SInv;
	SInv.coeffRef(0, 0) = std::complex<double>(1.0, 0.0);
	SInv.coeffRef(1, 1) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(1, 2) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(2, 3) = std::complex<double>(1.0, 0.0);
	SInv.coeffRef(3, 1) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(3, 2) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(4, 4) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(4, 5) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(5, 6) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(5, 7) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(6, 8) = std::complex<double>(1.0, 0.0);
	SInv.coeffRef(7, 6) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(7, 7) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(8, 4) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(8, 5) = std::complex<double>(0.0, -0.7071067811865476);
	SInv.coeffRef(9, 9) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(9, 10) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(10, 11) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(10, 12) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(11, 13) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(11, 14) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(12, 15) = std::complex<double>(1.0, 0.0);
	SInv.coeffRef(13, 13) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(13, 14) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(14, 11) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(14, 12) = std::complex<double>(0.0, -0.7071067811865476);
	SInv.coeffRef(15, 9) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(15, 10) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(16, 16) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(16, 17) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(17, 18) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(17, 19) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(18, 20) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(18, 21) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(19, 22) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(19, 23) = std::complex<double>(0.0, 0.7071067811865476);
	SInv.coeffRef(20, 24) = std::complex<double>(1.0, 0.0);
	SInv.coeffRef(21, 22) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(21, 23) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(22, 20) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(22, 21) = std::complex<double>(0.0, -0.7071067811865476);
	SInv.coeffRef(23, 18) = std::complex<double>(-0.7071067811865476, 0.0);
	SInv.coeffRef(23, 19) = std::complex<double>(-0.0, 0.7071067811865476);
	SInv.coeffRef(24, 16) = std::complex<double>(0.7071067811865476, 0.0);
	SInv.coeffRef(24, 17) = std::complex<double>(0.0, -0.7071067811865476);

	//Producing complex-valued matrices =============
	//M_0dxL + M_1dyL + M_2dzL + M_3L = b

	//M_0 ---
	// is constant

	//M_1 ---
	// is constant

	//M_2 ---
	// is constant

	//M_3 ---
	Eigen::Matrix<double, 25, 25> M_3_real_staggered[8];
	for( int i=0;i<8;++i )
	{
		Eigen::Matrix<std::complex<double>, 25, 25> M_3;
		M_3(0, 0) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(0, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(1, 1) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(1, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(2, 2) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(1, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(3, 3) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(1, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(4, 4) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(5, 5) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(6, 6) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(7, 7) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(8, 8) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(9, 9) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(10, 10) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(11, 11) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(12, 12) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(13, 13) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(14, 14) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(15, 15) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(16, 16) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(17, 17) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(18, 18) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(19, 19) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(20, 20) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(21, 21) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(22, 22) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(23, 23) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3(24, 24) = (problem.evalExtinction(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]+
			-(problem.evalScattering(domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]*problem.evalPhase(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel]));
		M_3_real_staggered[i] = (S*M_3*SInv).real();
	}
	Eigen::Matrix<double, 25, 25> M_3_real;
	M_3_real.row(0) = M_3_real_staggered[2].row(0);
	M_3_real.row(1) = M_3_real_staggered[3].row(1);
	M_3_real.row(2) = M_3_real_staggered[1].row(2);
	M_3_real.row(3) = M_3_real_staggered[6].row(3);
	M_3_real.row(4) = M_3_real_staggered[2].row(4);
	M_3_real.row(5) = M_3_real_staggered[0].row(5);
	M_3_real.row(6) = M_3_real_staggered[7].row(6);
	M_3_real.row(7) = M_3_real_staggered[5].row(7);
	M_3_real.row(8) = M_3_real_staggered[2].row(8);
	M_3_real.row(9) = M_3_real_staggered[3].row(9);
	M_3_real.row(10) = M_3_real_staggered[1].row(10);
	M_3_real.row(11) = M_3_real_staggered[6].row(11);
	M_3_real.row(12) = M_3_real_staggered[4].row(12);
	M_3_real.row(13) = M_3_real_staggered[3].row(13);
	M_3_real.row(14) = M_3_real_staggered[1].row(14);
	M_3_real.row(15) = M_3_real_staggered[6].row(15);
	M_3_real.row(16) = M_3_real_staggered[2].row(16);
	M_3_real.row(17) = M_3_real_staggered[0].row(17);
	M_3_real.row(18) = M_3_real_staggered[7].row(18);
	M_3_real.row(19) = M_3_real_staggered[5].row(19);
	M_3_real.row(20) = M_3_real_staggered[2].row(20);
	M_3_real.row(21) = M_3_real_staggered[0].row(21);
	M_3_real.row(22) = M_3_real_staggered[7].row(22);
	M_3_real.row(23) = M_3_real_staggered[5].row(23);
	M_3_real.row(24) = M_3_real_staggered[2].row(24);

	//b ---
	Eigen::Matrix<double, 25, 1> b_real_staggered[8];
	for( int i=0;i<8;++i )
	{
		Eigen::Matrix<std::complex<double>, 25, 1> b;
		b(0, 0) = problem.evalEmission(0, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(1, 0) = problem.evalEmission(1, -1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(2, 0) = problem.evalEmission(1, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(3, 0) = problem.evalEmission(1, 1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(4, 0) = problem.evalEmission(2, -2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(5, 0) = problem.evalEmission(2, -1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(6, 0) = problem.evalEmission(2, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(7, 0) = problem.evalEmission(2, 1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(8, 0) = problem.evalEmission(2, 2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(9, 0) = problem.evalEmission(3, -3, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(10, 0) = problem.evalEmission(3, -2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(11, 0) = problem.evalEmission(3, -1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(12, 0) = problem.evalEmission(3, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(13, 0) = problem.evalEmission(3, 1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(14, 0) = problem.evalEmission(3, 2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(15, 0) = problem.evalEmission(3, 3, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(16, 0) = problem.evalEmission(4, -4, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(17, 0) = problem.evalEmission(4, -3, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(18, 0) = problem.evalEmission(4, -2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(19, 0) = problem.evalEmission(4, -1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(20, 0) = problem.evalEmission(4, 0, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(21, 0) = problem.evalEmission(4, 1, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(22, 0) = problem.evalEmission(4, 2, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(23, 0) = problem.evalEmission(4, 3, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b(24, 0) = problem.evalEmission(4, 4, domain.voxelToWorld(vd+ctx.getVoxelSpaceOffsetFromGrid2(i)))[color_channel];
		b_real_staggered[i] = (S*b).real();
	}
	Eigen::Matrix<double, 25, 1> b_real;
	b_real.row(0) = b_real_staggered[2].row(0);
	b_real.row(1) = b_real_staggered[3].row(1);
	b_real.row(2) = b_real_staggered[1].row(2);
	b_real.row(3) = b_real_staggered[6].row(3);
	b_real.row(4) = b_real_staggered[2].row(4);
	b_real.row(5) = b_real_staggered[0].row(5);
	b_real.row(6) = b_real_staggered[7].row(6);
	b_real.row(7) = b_real_staggered[5].row(7);
	b_real.row(8) = b_real_staggered[2].row(8);
	b_real.row(9) = b_real_staggered[3].row(9);
	b_real.row(10) = b_real_staggered[1].row(10);
	b_real.row(11) = b_real_staggered[6].row(11);
	b_real.row(12) = b_real_staggered[4].row(12);
	b_real.row(13) = b_real_staggered[3].row(13);
	b_real.row(14) = b_real_staggered[1].row(14);
	b_real.row(15) = b_real_staggered[6].row(15);
	b_real.row(16) = b_real_staggered[2].row(16);
	b_real.row(17) = b_real_staggered[0].row(17);
	b_real.row(18) = b_real_staggered[7].row(18);
	b_real.row(19) = b_real_staggered[5].row(19);
	b_real.row(20) = b_real_staggered[2].row(20);
	b_real.row(21) = b_real_staggered[0].row(21);
	b_real.row(22) = b_real_staggered[7].row(22);
	b_real.row(23) = b_real_staggered[5].row(23);
	b_real.row(24) = b_real_staggered[2].row(24);

	// Assembling global system =============
	ctx.coeff_A( 1, vi + V3i(-1,0,0), 0 ) += -(h_inv[0]*0.57735026919);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 0 ) += (h_inv[0]*0.57735026919);
	ctx.coeff_A( 0, vi + V3i(0,0,0), 1 ) += -(h_inv[0]*0.57735026919);
	ctx.coeff_A( 0, vi + V3i(1,0,0), 1 ) += (h_inv[0]*0.57735026919);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 1 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 4, vi + V3i(1,0,0), 1 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 1 ) += -(h_inv[0]*-0.258198889747);
	ctx.coeff_A( 8, vi + V3i(1,0,0), 1 ) += (h_inv[0]*-0.258198889747);
	ctx.coeff_A( 5, vi + V3i(-1,0,0), 2 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 2 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 6, vi + V3i(-1,0,0), 3 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 3 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 1, vi + V3i(-1,0,0), 4 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 4 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 9, vi + V3i(-1,0,0), 4 ) += -(h_inv[0]*0.462910049886);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 4 ) += (h_inv[0]*0.462910049886);
	ctx.coeff_A( 13, vi + V3i(-1,0,0), 4 ) += -(h_inv[0]*-0.119522860933);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 4 ) += (h_inv[0]*-0.119522860933);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 5 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 2, vi + V3i(1,0,0), 5 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 5 ) += -(h_inv[0]*0.462910049886);
	ctx.coeff_A( 10, vi + V3i(1,0,0), 5 ) += (h_inv[0]*0.462910049886);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 5 ) += -(h_inv[0]*-0.119522860933);
	ctx.coeff_A( 14, vi + V3i(1,0,0), 5 ) += (h_inv[0]*-0.119522860933);
	ctx.coeff_A( 3, vi + V3i(0,0,0), 6 ) += -(h_inv[0]*0.4472135955);
	ctx.coeff_A( 3, vi + V3i(1,0,0), 6 ) += (h_inv[0]*0.4472135955);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 6 ) += -(h_inv[0]*0.377964473009);
	ctx.coeff_A( 11, vi + V3i(1,0,0), 6 ) += (h_inv[0]*0.377964473009);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 6 ) += -(h_inv[0]*-0.292770021885);
	ctx.coeff_A( 15, vi + V3i(1,0,0), 6 ) += (h_inv[0]*-0.292770021885);
	ctx.coeff_A( 12, vi + V3i(-1,0,0), 7 ) += -(h_inv[0]*0.377964473009);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 7 ) += (h_inv[0]*0.377964473009);
	ctx.coeff_A( 1, vi + V3i(-1,0,0), 8 ) += -(h_inv[0]*-0.258198889747);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 8 ) += (h_inv[0]*-0.258198889747);
	ctx.coeff_A( 13, vi + V3i(-1,0,0), 8 ) += -(h_inv[0]*0.414039335605);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 8 ) += (h_inv[0]*0.414039335605);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 9 ) += -(h_inv[0]*0.462910049886);
	ctx.coeff_A( 4, vi + V3i(1,0,0), 9 ) += (h_inv[0]*0.462910049886);
	ctx.coeff_A( 16, vi + V3i(0,0,0), 9 ) += -(h_inv[0]*0.471404520791);
	ctx.coeff_A( 16, vi + V3i(1,0,0), 9 ) += (h_inv[0]*0.471404520791);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 9 ) += -(h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 20, vi + V3i(1,0,0), 9 ) += (h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 5, vi + V3i(-1,0,0), 10 ) += -(h_inv[0]*0.462910049886);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 10 ) += (h_inv[0]*0.462910049886);
	ctx.coeff_A( 17, vi + V3i(-1,0,0), 10 ) += -(h_inv[0]*0.471404520791);
	ctx.coeff_A( 17, vi + V3i(0,0,0), 10 ) += (h_inv[0]*0.471404520791);
	ctx.coeff_A( 21, vi + V3i(-1,0,0), 10 ) += -(h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 10 ) += (h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 6, vi + V3i(-1,0,0), 11 ) += -(h_inv[0]*0.377964473009);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 11 ) += (h_inv[0]*0.377964473009);
	ctx.coeff_A( 18, vi + V3i(-1,0,0), 11 ) += -(h_inv[0]*0.408248290464);
	ctx.coeff_A( 18, vi + V3i(0,0,0), 11 ) += (h_inv[0]*0.408248290464);
	ctx.coeff_A( 22, vi + V3i(-1,0,0), 11 ) += -(h_inv[0]*-0.154303349962);
	ctx.coeff_A( 22, vi + V3i(0,0,0), 11 ) += (h_inv[0]*-0.154303349962);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 12 ) += -(h_inv[0]*0.377964473009);
	ctx.coeff_A( 7, vi + V3i(1,0,0), 12 ) += (h_inv[0]*0.377964473009);
	ctx.coeff_A( 19, vi + V3i(0,0,0), 12 ) += -(h_inv[0]*0.408248290464);
	ctx.coeff_A( 19, vi + V3i(1,0,0), 12 ) += (h_inv[0]*0.408248290464);
	ctx.coeff_A( 23, vi + V3i(0,0,0), 12 ) += -(h_inv[0]*-0.154303349962);
	ctx.coeff_A( 23, vi + V3i(1,0,0), 12 ) += (h_inv[0]*-0.154303349962);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 13 ) += -(h_inv[0]*-0.119522860933);
	ctx.coeff_A( 4, vi + V3i(1,0,0), 13 ) += (h_inv[0]*-0.119522860933);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 13 ) += -(h_inv[0]*0.414039335605);
	ctx.coeff_A( 8, vi + V3i(1,0,0), 13 ) += (h_inv[0]*0.414039335605);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 13 ) += -(h_inv[0]*0.345032779671);
	ctx.coeff_A( 20, vi + V3i(1,0,0), 13 ) += (h_inv[0]*0.345032779671);
	ctx.coeff_A( 24, vi + V3i(0,0,0), 13 ) += -(h_inv[0]*-0.308606699924);
	ctx.coeff_A( 24, vi + V3i(1,0,0), 13 ) += (h_inv[0]*-0.308606699924);
	ctx.coeff_A( 5, vi + V3i(-1,0,0), 14 ) += -(h_inv[0]*-0.119522860933);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 14 ) += (h_inv[0]*-0.119522860933);
	ctx.coeff_A( 21, vi + V3i(-1,0,0), 14 ) += -(h_inv[0]*0.345032779671);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 14 ) += (h_inv[0]*0.345032779671);
	ctx.coeff_A( 6, vi + V3i(-1,0,0), 15 ) += -(h_inv[0]*-0.292770021885);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 15 ) += (h_inv[0]*-0.292770021885);
	ctx.coeff_A( 22, vi + V3i(-1,0,0), 15 ) += -(h_inv[0]*0.398409536445);
	ctx.coeff_A( 22, vi + V3i(0,0,0), 15 ) += (h_inv[0]*0.398409536445);
	ctx.coeff_A( 9, vi + V3i(-1,0,0), 16 ) += -(h_inv[0]*0.471404520791);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 16 ) += (h_inv[0]*0.471404520791);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 17 ) += -(h_inv[0]*0.471404520791);
	ctx.coeff_A( 10, vi + V3i(1,0,0), 17 ) += (h_inv[0]*0.471404520791);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 18 ) += -(h_inv[0]*0.408248290464);
	ctx.coeff_A( 11, vi + V3i(1,0,0), 18 ) += (h_inv[0]*0.408248290464);
	ctx.coeff_A( 12, vi + V3i(-1,0,0), 19 ) += -(h_inv[0]*0.408248290464);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 19 ) += (h_inv[0]*0.408248290464);
	ctx.coeff_A( 9, vi + V3i(-1,0,0), 20 ) += -(h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 20 ) += (h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 13, vi + V3i(-1,0,0), 20 ) += -(h_inv[0]*0.345032779671);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 20 ) += (h_inv[0]*0.345032779671);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 21 ) += -(h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 10, vi + V3i(1,0,0), 21 ) += (h_inv[0]*-0.0890870806375);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 21 ) += -(h_inv[0]*0.345032779671);
	ctx.coeff_A( 14, vi + V3i(1,0,0), 21 ) += (h_inv[0]*0.345032779671);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 22 ) += -(h_inv[0]*-0.154303349962);
	ctx.coeff_A( 11, vi + V3i(1,0,0), 22 ) += (h_inv[0]*-0.154303349962);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 22 ) += -(h_inv[0]*0.398409536445);
	ctx.coeff_A( 15, vi + V3i(1,0,0), 22 ) += (h_inv[0]*0.398409536445);
	ctx.coeff_A( 12, vi + V3i(-1,0,0), 23 ) += -(h_inv[0]*-0.154303349962);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 23 ) += (h_inv[0]*-0.154303349962);
	ctx.coeff_A( 13, vi + V3i(-1,0,0), 24 ) += -(h_inv[0]*-0.308606699924);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 24 ) += (h_inv[0]*-0.308606699924);
	ctx.coeff_A( 2, vi + V3i(0,-1,0), 0 ) += -(h_inv[1]*0.57735026919);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 0 ) += (h_inv[1]*0.57735026919);
	ctx.coeff_A( 5, vi + V3i(0,-1,0), 1 ) += -(h_inv[1]*0.4472135955);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 1 ) += (h_inv[1]*0.4472135955);
	ctx.coeff_A( 0, vi + V3i(0,0,0), 2 ) += -(h_inv[1]*0.57735026919);
	ctx.coeff_A( 0, vi + V3i(0,1,0), 2 ) += (h_inv[1]*0.57735026919);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 2 ) += -(h_inv[1]*-0.4472135955);
	ctx.coeff_A( 4, vi + V3i(0,1,0), 2 ) += (h_inv[1]*-0.4472135955);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 2 ) += -(h_inv[1]*-0.258198889747);
	ctx.coeff_A( 8, vi + V3i(0,1,0), 2 ) += (h_inv[1]*-0.258198889747);
	ctx.coeff_A( 7, vi + V3i(0,-1,0), 3 ) += -(h_inv[1]*0.4472135955);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 3 ) += (h_inv[1]*0.4472135955);
	ctx.coeff_A( 2, vi + V3i(0,-1,0), 4 ) += -(h_inv[1]*-0.4472135955);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 4 ) += (h_inv[1]*-0.4472135955);
	ctx.coeff_A( 10, vi + V3i(0,-1,0), 4 ) += -(h_inv[1]*0.462910049886);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 4 ) += (h_inv[1]*0.462910049886);
	ctx.coeff_A( 14, vi + V3i(0,-1,0), 4 ) += -(h_inv[1]*0.119522860933);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 4 ) += (h_inv[1]*0.119522860933);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 5 ) += -(h_inv[1]*0.4472135955);
	ctx.coeff_A( 1, vi + V3i(0,1,0), 5 ) += (h_inv[1]*0.4472135955);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 5 ) += -(h_inv[1]*-0.462910049886);
	ctx.coeff_A( 9, vi + V3i(0,1,0), 5 ) += (h_inv[1]*-0.462910049886);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 5 ) += -(h_inv[1]*-0.119522860933);
	ctx.coeff_A( 13, vi + V3i(0,1,0), 5 ) += (h_inv[1]*-0.119522860933);
	ctx.coeff_A( 12, vi + V3i(0,-1,0), 6 ) += -(h_inv[1]*0.377964473009);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 6 ) += (h_inv[1]*0.377964473009);
	ctx.coeff_A( 3, vi + V3i(0,0,0), 7 ) += -(h_inv[1]*0.4472135955);
	ctx.coeff_A( 3, vi + V3i(0,1,0), 7 ) += (h_inv[1]*0.4472135955);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 7 ) += -(h_inv[1]*-0.377964473009);
	ctx.coeff_A( 11, vi + V3i(0,1,0), 7 ) += (h_inv[1]*-0.377964473009);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 7 ) += -(h_inv[1]*-0.292770021885);
	ctx.coeff_A( 15, vi + V3i(0,1,0), 7 ) += (h_inv[1]*-0.292770021885);
	ctx.coeff_A( 2, vi + V3i(0,-1,0), 8 ) += -(h_inv[1]*-0.258198889747);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 8 ) += (h_inv[1]*-0.258198889747);
	ctx.coeff_A( 14, vi + V3i(0,-1,0), 8 ) += -(h_inv[1]*0.414039335605);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 8 ) += (h_inv[1]*0.414039335605);
	ctx.coeff_A( 5, vi + V3i(0,-1,0), 9 ) += -(h_inv[1]*-0.462910049886);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 9 ) += (h_inv[1]*-0.462910049886);
	ctx.coeff_A( 17, vi + V3i(0,-1,0), 9 ) += -(h_inv[1]*0.471404520791);
	ctx.coeff_A( 17, vi + V3i(0,0,0), 9 ) += (h_inv[1]*0.471404520791);
	ctx.coeff_A( 21, vi + V3i(0,-1,0), 9 ) += -(h_inv[1]*0.0890870806375);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 9 ) += (h_inv[1]*0.0890870806375);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 10 ) += -(h_inv[1]*0.462910049886);
	ctx.coeff_A( 4, vi + V3i(0,1,0), 10 ) += (h_inv[1]*0.462910049886);
	ctx.coeff_A( 16, vi + V3i(0,0,0), 10 ) += -(h_inv[1]*-0.471404520791);
	ctx.coeff_A( 16, vi + V3i(0,1,0), 10 ) += (h_inv[1]*-0.471404520791);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 10 ) += -(h_inv[1]*-0.0890870806375);
	ctx.coeff_A( 20, vi + V3i(0,1,0), 10 ) += (h_inv[1]*-0.0890870806375);
	ctx.coeff_A( 7, vi + V3i(0,-1,0), 11 ) += -(h_inv[1]*-0.377964473009);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 11 ) += (h_inv[1]*-0.377964473009);
	ctx.coeff_A( 19, vi + V3i(0,-1,0), 11 ) += -(h_inv[1]*0.408248290464);
	ctx.coeff_A( 19, vi + V3i(0,0,0), 11 ) += (h_inv[1]*0.408248290464);
	ctx.coeff_A( 23, vi + V3i(0,-1,0), 11 ) += -(h_inv[1]*0.154303349962);
	ctx.coeff_A( 23, vi + V3i(0,0,0), 11 ) += (h_inv[1]*0.154303349962);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 12 ) += -(h_inv[1]*0.377964473009);
	ctx.coeff_A( 6, vi + V3i(0,1,0), 12 ) += (h_inv[1]*0.377964473009);
	ctx.coeff_A( 18, vi + V3i(0,0,0), 12 ) += -(h_inv[1]*-0.408248290464);
	ctx.coeff_A( 18, vi + V3i(0,1,0), 12 ) += (h_inv[1]*-0.408248290464);
	ctx.coeff_A( 22, vi + V3i(0,0,0), 12 ) += -(h_inv[1]*-0.154303349962);
	ctx.coeff_A( 22, vi + V3i(0,1,0), 12 ) += (h_inv[1]*-0.154303349962);
	ctx.coeff_A( 5, vi + V3i(0,-1,0), 13 ) += -(h_inv[1]*-0.119522860933);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 13 ) += (h_inv[1]*-0.119522860933);
	ctx.coeff_A( 21, vi + V3i(0,-1,0), 13 ) += -(h_inv[1]*0.345032779671);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 13 ) += (h_inv[1]*0.345032779671);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 14 ) += -(h_inv[1]*0.119522860933);
	ctx.coeff_A( 4, vi + V3i(0,1,0), 14 ) += (h_inv[1]*0.119522860933);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 14 ) += -(h_inv[1]*0.414039335605);
	ctx.coeff_A( 8, vi + V3i(0,1,0), 14 ) += (h_inv[1]*0.414039335605);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 14 ) += -(h_inv[1]*-0.345032779671);
	ctx.coeff_A( 20, vi + V3i(0,1,0), 14 ) += (h_inv[1]*-0.345032779671);
	ctx.coeff_A( 24, vi + V3i(0,0,0), 14 ) += -(h_inv[1]*-0.308606699924);
	ctx.coeff_A( 24, vi + V3i(0,1,0), 14 ) += (h_inv[1]*-0.308606699924);
	ctx.coeff_A( 7, vi + V3i(0,-1,0), 15 ) += -(h_inv[1]*-0.292770021885);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 15 ) += (h_inv[1]*-0.292770021885);
	ctx.coeff_A( 23, vi + V3i(0,-1,0), 15 ) += -(h_inv[1]*0.398409536445);
	ctx.coeff_A( 23, vi + V3i(0,0,0), 15 ) += (h_inv[1]*0.398409536445);
	ctx.coeff_A( 10, vi + V3i(0,-1,0), 16 ) += -(h_inv[1]*-0.471404520791);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 16 ) += (h_inv[1]*-0.471404520791);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 17 ) += -(h_inv[1]*0.471404520791);
	ctx.coeff_A( 9, vi + V3i(0,1,0), 17 ) += (h_inv[1]*0.471404520791);
	ctx.coeff_A( 12, vi + V3i(0,-1,0), 18 ) += -(h_inv[1]*-0.408248290464);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 18 ) += (h_inv[1]*-0.408248290464);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 19 ) += -(h_inv[1]*0.408248290464);
	ctx.coeff_A( 11, vi + V3i(0,1,0), 19 ) += (h_inv[1]*0.408248290464);
	ctx.coeff_A( 10, vi + V3i(0,-1,0), 20 ) += -(h_inv[1]*-0.0890870806375);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 20 ) += (h_inv[1]*-0.0890870806375);
	ctx.coeff_A( 14, vi + V3i(0,-1,0), 20 ) += -(h_inv[1]*-0.345032779671);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 20 ) += (h_inv[1]*-0.345032779671);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 21 ) += -(h_inv[1]*0.0890870806375);
	ctx.coeff_A( 9, vi + V3i(0,1,0), 21 ) += (h_inv[1]*0.0890870806375);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 21 ) += -(h_inv[1]*0.345032779671);
	ctx.coeff_A( 13, vi + V3i(0,1,0), 21 ) += (h_inv[1]*0.345032779671);
	ctx.coeff_A( 12, vi + V3i(0,-1,0), 22 ) += -(h_inv[1]*-0.154303349962);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 22 ) += (h_inv[1]*-0.154303349962);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 23 ) += -(h_inv[1]*0.154303349962);
	ctx.coeff_A( 11, vi + V3i(0,1,0), 23 ) += (h_inv[1]*0.154303349962);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 23 ) += -(h_inv[1]*0.398409536445);
	ctx.coeff_A( 15, vi + V3i(0,1,0), 23 ) += (h_inv[1]*0.398409536445);
	ctx.coeff_A( 14, vi + V3i(0,-1,0), 24 ) += -(h_inv[1]*-0.308606699924);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 24 ) += (h_inv[1]*-0.308606699924);
	ctx.coeff_A( 3, vi + V3i(0,0,-1), 0 ) += -(h_inv[2]*0.57735026919);
	ctx.coeff_A( 3, vi + V3i(0,0,0), 0 ) += (h_inv[2]*0.57735026919);
	ctx.coeff_A( 6, vi + V3i(0,0,-1), 1 ) += -(h_inv[2]*0.4472135955);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 1 ) += (h_inv[2]*0.4472135955);
	ctx.coeff_A( 7, vi + V3i(0,0,-1), 2 ) += -(h_inv[2]*0.4472135955);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 2 ) += (h_inv[2]*0.4472135955);
	ctx.coeff_A( 0, vi + V3i(0,0,0), 3 ) += -(h_inv[2]*0.57735026919);
	ctx.coeff_A( 0, vi + V3i(0,0,1), 3 ) += (h_inv[2]*0.57735026919);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 3 ) += -(h_inv[2]*0.516397779494);
	ctx.coeff_A( 8, vi + V3i(0,0,1), 3 ) += (h_inv[2]*0.516397779494);
	ctx.coeff_A( 11, vi + V3i(0,0,-1), 4 ) += -(h_inv[2]*0.377964473009);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 4 ) += (h_inv[2]*0.377964473009);
	ctx.coeff_A( 12, vi + V3i(0,0,-1), 5 ) += -(h_inv[2]*0.377964473009);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 5 ) += (h_inv[2]*0.377964473009);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 6 ) += -(h_inv[2]*0.4472135955);
	ctx.coeff_A( 1, vi + V3i(0,0,1), 6 ) += (h_inv[2]*0.4472135955);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 6 ) += -(h_inv[2]*0.478091443734);
	ctx.coeff_A( 13, vi + V3i(0,0,1), 6 ) += (h_inv[2]*0.478091443734);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 7 ) += -(h_inv[2]*0.4472135955);
	ctx.coeff_A( 2, vi + V3i(0,0,1), 7 ) += (h_inv[2]*0.4472135955);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 7 ) += -(h_inv[2]*0.478091443734);
	ctx.coeff_A( 14, vi + V3i(0,0,1), 7 ) += (h_inv[2]*0.478091443734);
	ctx.coeff_A( 3, vi + V3i(0,0,-1), 8 ) += -(h_inv[2]*0.516397779494);
	ctx.coeff_A( 3, vi + V3i(0,0,0), 8 ) += (h_inv[2]*0.516397779494);
	ctx.coeff_A( 15, vi + V3i(0,0,-1), 8 ) += -(h_inv[2]*0.507092552837);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 8 ) += (h_inv[2]*0.507092552837);
	ctx.coeff_A( 18, vi + V3i(0,0,-1), 9 ) += -(h_inv[2]*0.333333333333);
	ctx.coeff_A( 18, vi + V3i(0,0,0), 9 ) += (h_inv[2]*0.333333333333);
	ctx.coeff_A( 19, vi + V3i(0,0,-1), 10 ) += -(h_inv[2]*0.333333333333);
	ctx.coeff_A( 19, vi + V3i(0,0,0), 10 ) += (h_inv[2]*0.333333333333);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 11 ) += -(h_inv[2]*0.377964473009);
	ctx.coeff_A( 4, vi + V3i(0,0,1), 11 ) += (h_inv[2]*0.377964473009);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 11 ) += -(h_inv[2]*0.436435780472);
	ctx.coeff_A( 20, vi + V3i(0,0,1), 11 ) += (h_inv[2]*0.436435780472);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 12 ) += -(h_inv[2]*0.377964473009);
	ctx.coeff_A( 5, vi + V3i(0,0,1), 12 ) += (h_inv[2]*0.377964473009);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 12 ) += -(h_inv[2]*0.436435780472);
	ctx.coeff_A( 21, vi + V3i(0,0,1), 12 ) += (h_inv[2]*0.436435780472);
	ctx.coeff_A( 6, vi + V3i(0,0,-1), 13 ) += -(h_inv[2]*0.478091443734);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 13 ) += (h_inv[2]*0.478091443734);
	ctx.coeff_A( 22, vi + V3i(0,0,-1), 13 ) += -(h_inv[2]*0.487950036474);
	ctx.coeff_A( 22, vi + V3i(0,0,0), 13 ) += (h_inv[2]*0.487950036474);
	ctx.coeff_A( 7, vi + V3i(0,0,-1), 14 ) += -(h_inv[2]*0.478091443734);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 14 ) += (h_inv[2]*0.478091443734);
	ctx.coeff_A( 23, vi + V3i(0,0,-1), 14 ) += -(h_inv[2]*0.487950036474);
	ctx.coeff_A( 23, vi + V3i(0,0,0), 14 ) += (h_inv[2]*0.487950036474);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 15 ) += -(h_inv[2]*0.507092552837);
	ctx.coeff_A( 8, vi + V3i(0,0,1), 15 ) += (h_inv[2]*0.507092552837);
	ctx.coeff_A( 24, vi + V3i(0,0,0), 15 ) += -(h_inv[2]*0.503952630679);
	ctx.coeff_A( 24, vi + V3i(0,0,1), 15 ) += (h_inv[2]*0.503952630679);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 18 ) += -(h_inv[2]*0.333333333333);
	ctx.coeff_A( 9, vi + V3i(0,0,1), 18 ) += (h_inv[2]*0.333333333333);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 19 ) += -(h_inv[2]*0.333333333333);
	ctx.coeff_A( 10, vi + V3i(0,0,1), 19 ) += (h_inv[2]*0.333333333333);
	ctx.coeff_A( 11, vi + V3i(0,0,-1), 20 ) += -(h_inv[2]*0.436435780472);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 20 ) += (h_inv[2]*0.436435780472);
	ctx.coeff_A( 12, vi + V3i(0,0,-1), 21 ) += -(h_inv[2]*0.436435780472);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 21 ) += (h_inv[2]*0.436435780472);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 22 ) += -(h_inv[2]*0.487950036474);
	ctx.coeff_A( 13, vi + V3i(0,0,1), 22 ) += (h_inv[2]*0.487950036474);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 23 ) += -(h_inv[2]*0.487950036474);
	ctx.coeff_A( 14, vi + V3i(0,0,1), 23 ) += (h_inv[2]*0.487950036474);
	ctx.coeff_A( 15, vi + V3i(0,0,-1), 24 ) += -(h_inv[2]*0.503952630679);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 24 ) += (h_inv[2]*0.503952630679);
	ctx.coeff_A( 0, vi + V3i(0,0,0), 0 ) += M_3_real.coeffRef(0, 0);
	ctx.coeff_A( 1, vi + V3i(0,0,0), 1 ) += M_3_real.coeffRef(1, 1);
	ctx.coeff_A( 2, vi + V3i(0,0,0), 2 ) += M_3_real.coeffRef(2, 2);
	ctx.coeff_A( 3, vi + V3i(0,0,0), 3 ) += M_3_real.coeffRef(3, 3);
	ctx.coeff_A( 4, vi + V3i(0,0,0), 4 ) += M_3_real.coeffRef(4, 4);
	ctx.coeff_A( 5, vi + V3i(0,0,0), 5 ) += M_3_real.coeffRef(5, 5);
	ctx.coeff_A( 6, vi + V3i(0,0,0), 6 ) += M_3_real.coeffRef(6, 6);
	ctx.coeff_A( 7, vi + V3i(0,0,0), 7 ) += M_3_real.coeffRef(7, 7);
	ctx.coeff_A( 8, vi + V3i(0,0,0), 8 ) += M_3_real.coeffRef(8, 8);
	ctx.coeff_A( 9, vi + V3i(0,0,0), 9 ) += M_3_real.coeffRef(9, 9);
	ctx.coeff_A( 10, vi + V3i(0,0,0), 10 ) += M_3_real.coeffRef(10, 10);
	ctx.coeff_A( 11, vi + V3i(0,0,0), 11 ) += M_3_real.coeffRef(11, 11);
	ctx.coeff_A( 12, vi + V3i(0,0,0), 12 ) += M_3_real.coeffRef(12, 12);
	ctx.coeff_A( 13, vi + V3i(0,0,0), 13 ) += M_3_real.coeffRef(13, 13);
	ctx.coeff_A( 14, vi + V3i(0,0,0), 14 ) += M_3_real.coeffRef(14, 14);
	ctx.coeff_A( 15, vi + V3i(0,0,0), 15 ) += M_3_real.coeffRef(15, 15);
	ctx.coeff_A( 16, vi + V3i(0,0,0), 16 ) += M_3_real.coeffRef(16, 16);
	ctx.coeff_A( 17, vi + V3i(0,0,0), 17 ) += M_3_real.coeffRef(17, 17);
	ctx.coeff_A( 18, vi + V3i(0,0,0), 18 ) += M_3_real.coeffRef(18, 18);
	ctx.coeff_A( 19, vi + V3i(0,0,0), 19 ) += M_3_real.coeffRef(19, 19);
	ctx.coeff_A( 20, vi + V3i(0,0,0), 20 ) += M_3_real.coeffRef(20, 20);
	ctx.coeff_A( 21, vi + V3i(0,0,0), 21 ) += M_3_real.coeffRef(21, 21);
	ctx.coeff_A( 22, vi + V3i(0,0,0), 22 ) += M_3_real.coeffRef(22, 22);
	ctx.coeff_A( 23, vi + V3i(0,0,0), 23 ) += M_3_real.coeffRef(23, 23);
	ctx.coeff_A( 24, vi + V3i(0,0,0), 24 ) += M_3_real.coeffRef(24, 24);
	ctx.coeff_b( 0 ) += b_real.coeffRef(0, 0);
	ctx.coeff_b( 1 ) += b_real.coeffRef(1, 0);
	ctx.coeff_b( 2 ) += b_real.coeffRef(2, 0);
	ctx.coeff_b( 3 ) += b_real.coeffRef(3, 0);
	ctx.coeff_b( 4 ) += b_real.coeffRef(4, 0);
	ctx.coeff_b( 5 ) += b_real.coeffRef(5, 0);
	ctx.coeff_b( 6 ) += b_real.coeffRef(6, 0);
	ctx.coeff_b( 7 ) += b_real.coeffRef(7, 0);
	ctx.coeff_b( 8 ) += b_real.coeffRef(8, 0);
	ctx.coeff_b( 9 ) += b_real.coeffRef(9, 0);
	ctx.coeff_b( 10 ) += b_real.coeffRef(10, 0);
	ctx.coeff_b( 11 ) += b_real.coeffRef(11, 0);
	ctx.coeff_b( 12 ) += b_real.coeffRef(12, 0);
	ctx.coeff_b( 13 ) += b_real.coeffRef(13, 0);
	ctx.coeff_b( 14 ) += b_real.coeffRef(14, 0);
	ctx.coeff_b( 15 ) += b_real.coeffRef(15, 0);
	ctx.coeff_b( 16 ) += b_real.coeffRef(16, 0);
	ctx.coeff_b( 17 ) += b_real.coeffRef(17, 0);
	ctx.coeff_b( 18 ) += b_real.coeffRef(18, 0);
	ctx.coeff_b( 19 ) += b_real.coeffRef(19, 0);
	ctx.coeff_b( 20 ) += b_real.coeffRef(20, 0);
	ctx.coeff_b( 21 ) += b_real.coeffRef(21, 0);
	ctx.coeff_b( 22 ) += b_real.coeffRef(22, 0);
	ctx.coeff_b( 23 ) += b_real.coeffRef(23, 0);
	ctx.coeff_b( 24 ) += b_real.coeffRef(24, 0);
}
V3i stencil_fopn_p4_sg_get_offset(int coeff)
{
	switch(coeff)
	{
		case 0:return V3i(1, 1, 1);break;
		case 1:return V3i(0, 1, 1);break;
		case 2:return V3i(1, 0, 1);break;
		case 3:return V3i(1, 1, 0);break;
		case 4:return V3i(1, 1, 1);break;
		case 5:return V3i(0, 0, 1);break;
		case 6:return V3i(0, 1, 0);break;
		case 7:return V3i(1, 0, 0);break;
		case 8:return V3i(1, 1, 1);break;
		case 9:return V3i(0, 1, 1);break;
		case 10:return V3i(1, 0, 1);break;
		case 11:return V3i(1, 1, 0);break;
		case 12:return V3i(0, 0, 0);break;
		case 13:return V3i(0, 1, 1);break;
		case 14:return V3i(1, 0, 1);break;
		case 15:return V3i(1, 1, 0);break;
		case 16:return V3i(1, 1, 1);break;
		case 17:return V3i(0, 0, 1);break;
		case 18:return V3i(0, 1, 0);break;
		case 19:return V3i(1, 0, 0);break;
		case 20:return V3i(1, 1, 1);break;
		case 21:return V3i(0, 0, 1);break;
		case 22:return V3i(0, 1, 0);break;
		case 23:return V3i(1, 0, 0);break;
		case 24:return V3i(1, 1, 1);break;
		default:throw std::runtime_error("unexpected coefficient index");break;
	};
}
REGISTER_STENCIL(stencil_fopn_p4_sg, 4, 25, 1)
