// This file was generated by stencil2.py on Friday, 16. February 2018 08:43PM

#include <PNSystem.h>

void stencil_p4_3d_cg(PNSystem::Stencil::Context& ctx)
{
	V3i vi = ctx.getVoxelCoord();
	V3d vd = vi.cast<double>();
	const Domain& domain = ctx.getDomain();
	const PNVolume& problem = ctx.getProblem();
	V3d h_inv( 1.0/(2*domain.getVoxelSize()[0]), 1.0/(2*domain.getVoxelSize()[1]), 1.0/(2*domain.getVoxelSize()[2]) );
	int color_channel = 0;

	// row=0 l=0 m=0 --------------------------
	ctx.coeff_A( 0, vi+V3i(-1, 0, 0), 3 ) += (0.57735026919*h_inv[0]);
	ctx.coeff_A( 0, vi+V3i(1, 0, 0), 3 ) += -(0.57735026919*h_inv[0]);
	ctx.coeff_A( 0, vi+V3i(0, -1, 0), 1 ) += (0.57735026919*h_inv[1]);
	ctx.coeff_A( 0, vi+V3i(0, 1, 0), 1 ) += -(0.57735026919*h_inv[1]);
	ctx.coeff_A( 0, vi+V3i(0, 0, -1), 2 ) += -(0.57735026919*h_inv[2]);
	ctx.coeff_A( 0, vi+V3i(0, 0, 1), 2 ) += (0.57735026919*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(3.54490770181*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(0, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 0, vi+V3i(0, 0, 0), 0 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(0, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 0 ) += c;
	}
	// row=1 l=1 m=-1 --------------------------
	ctx.coeff_A( 1, vi+V3i(0, -1, 0), 8 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(0, 1, 0), 8 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(0, -1, 0), 0 ) += (0.57735026919*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(0, 1, 0), 0 ) += -(0.57735026919*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(0, -1, 0), 6 ) += -(0.258198889747*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(0, 1, 0), 6 ) += (0.258198889747*h_inv[1]);
	ctx.coeff_A( 1, vi+V3i(-1, 0, 0), 4 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 1, vi+V3i(1, 0, 0), 4 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 1, vi+V3i(0, 0, -1), 5 ) += -(0.4472135955*h_inv[2]);
	ctx.coeff_A( 1, vi+V3i(0, 0, 1), 5 ) += (0.4472135955*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(2.04665341589*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(0, 0, 0), 1 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(1, -1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 1 ) += c;
	}
	// row=2 l=1 m=0 --------------------------
	ctx.coeff_A( 2, vi+V3i(-1, 0, 0), 7 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 2, vi+V3i(1, 0, 0), 7 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 2, vi+V3i(0, -1, 0), 5 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 2, vi+V3i(0, 1, 0), 5 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 2, vi+V3i(0, 0, -1), 0 ) += -(0.57735026919*h_inv[2]);
	ctx.coeff_A( 2, vi+V3i(0, 0, 1), 0 ) += (0.57735026919*h_inv[2]);
	ctx.coeff_A( 2, vi+V3i(0, 0, -1), 6 ) += -(0.516397779494*h_inv[2]);
	ctx.coeff_A( 2, vi+V3i(0, 0, 1), 6 ) += (0.516397779494*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(2.04665341589*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(0, 0, 0), 2 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(1, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 2 ) += c;
	}
	// row=3 l=1 m=1 --------------------------
	ctx.coeff_A( 3, vi+V3i(-1, 0, 0), 8 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(1, 0, 0), 8 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(-1, 0, 0), 0 ) += (0.57735026919*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(1, 0, 0), 0 ) += -(0.57735026919*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(-1, 0, 0), 6 ) += -(0.258198889747*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(1, 0, 0), 6 ) += (0.258198889747*h_inv[0]);
	ctx.coeff_A( 3, vi+V3i(0, -1, 0), 4 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 3, vi+V3i(0, 1, 0), 4 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 3, vi+V3i(0, 0, -1), 7 ) += -(0.4472135955*h_inv[2]);
	ctx.coeff_A( 3, vi+V3i(0, 0, 1), 7 ) += (0.4472135955*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(2.04665341589*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 3, vi+V3i(0, 0, 0), 3 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(1, 1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 3 ) += c;
	}
	// row=4 l=2 m=-2 --------------------------
	ctx.coeff_A( 4, vi+V3i(0, -1, 0), 15 ) += -(0.462910049886*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(0, 1, 0), 15 ) += (0.462910049886*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(0, -1, 0), 3 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(0, 1, 0), 3 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(0, -1, 0), 13 ) += -(0.119522860933*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(0, 1, 0), 13 ) += (0.119522860933*h_inv[1]);
	ctx.coeff_A( 4, vi+V3i(-1, 0, 0), 1 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(1, 0, 0), 1 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(-1, 0, 0), 11 ) += -(0.119522860933*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(1, 0, 0), 11 ) += (0.119522860933*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(-1, 0, 0), 9 ) += (0.462910049886*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(1, 0, 0), 9 ) += -(0.462910049886*h_inv[0]);
	ctx.coeff_A( 4, vi+V3i(0, 0, -1), 10 ) += -(0.377964473009*h_inv[2]);
	ctx.coeff_A( 4, vi+V3i(0, 0, 1), 10 ) += (0.377964473009*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.58533091904*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(2, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 4, vi+V3i(0, 0, 0), 4 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(2, -2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 4 ) += c;
	}
	// row=5 l=2 m=-1 --------------------------
	ctx.coeff_A( 5, vi+V3i(0, -1, 0), 14 ) += -(0.377964473009*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(0, 1, 0), 14 ) += (0.377964473009*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(0, -1, 0), 2 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(0, 1, 0), 2 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(0, -1, 0), 12 ) += -(0.292770021885*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(0, 1, 0), 12 ) += (0.292770021885*h_inv[1]);
	ctx.coeff_A( 5, vi+V3i(-1, 0, 0), 10 ) += (0.377964473009*h_inv[0]);
	ctx.coeff_A( 5, vi+V3i(1, 0, 0), 10 ) += -(0.377964473009*h_inv[0]);
	ctx.coeff_A( 5, vi+V3i(0, 0, -1), 1 ) += -(0.4472135955*h_inv[2]);
	ctx.coeff_A( 5, vi+V3i(0, 0, 1), 1 ) += (0.4472135955*h_inv[2]);
	ctx.coeff_A( 5, vi+V3i(0, 0, -1), 11 ) += -(0.478091443734*h_inv[2]);
	ctx.coeff_A( 5, vi+V3i(0, 0, 1), 11 ) += (0.478091443734*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.58533091904*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(2, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 5, vi+V3i(0, 0, 0), 5 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(2, -1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 5 ) += c;
	}
	// row=6 l=2 m=0 --------------------------
	ctx.coeff_A( 6, vi+V3i(-1, 0, 0), 3 ) += -(0.258198889747*h_inv[0]);
	ctx.coeff_A( 6, vi+V3i(1, 0, 0), 3 ) += (0.258198889747*h_inv[0]);
	ctx.coeff_A( 6, vi+V3i(-1, 0, 0), 13 ) += (0.414039335605*h_inv[0]);
	ctx.coeff_A( 6, vi+V3i(1, 0, 0), 13 ) += -(0.414039335605*h_inv[0]);
	ctx.coeff_A( 6, vi+V3i(0, -1, 0), 1 ) += -(0.258198889747*h_inv[1]);
	ctx.coeff_A( 6, vi+V3i(0, 1, 0), 1 ) += (0.258198889747*h_inv[1]);
	ctx.coeff_A( 6, vi+V3i(0, -1, 0), 11 ) += (0.414039335605*h_inv[1]);
	ctx.coeff_A( 6, vi+V3i(0, 1, 0), 11 ) += -(0.414039335605*h_inv[1]);
	ctx.coeff_A( 6, vi+V3i(0, 0, -1), 2 ) += -(0.516397779494*h_inv[2]);
	ctx.coeff_A( 6, vi+V3i(0, 0, 1), 2 ) += (0.516397779494*h_inv[2]);
	ctx.coeff_A( 6, vi+V3i(0, 0, -1), 12 ) += -(0.507092552837*h_inv[2]);
	ctx.coeff_A( 6, vi+V3i(0, 0, 1), 12 ) += (0.507092552837*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.58533091904*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(2, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 6, vi+V3i(0, 0, 0), 6 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(2, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 6 ) += c;
	}
	// row=7 l=2 m=1 --------------------------
	ctx.coeff_A( 7, vi+V3i(-1, 0, 0), 14 ) += (0.377964473009*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(1, 0, 0), 14 ) += -(0.377964473009*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(-1, 0, 0), 2 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(1, 0, 0), 2 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(-1, 0, 0), 12 ) += -(0.292770021885*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(1, 0, 0), 12 ) += (0.292770021885*h_inv[0]);
	ctx.coeff_A( 7, vi+V3i(0, -1, 0), 10 ) += (0.377964473009*h_inv[1]);
	ctx.coeff_A( 7, vi+V3i(0, 1, 0), 10 ) += -(0.377964473009*h_inv[1]);
	ctx.coeff_A( 7, vi+V3i(0, 0, -1), 3 ) += -(0.4472135955*h_inv[2]);
	ctx.coeff_A( 7, vi+V3i(0, 0, 1), 3 ) += (0.4472135955*h_inv[2]);
	ctx.coeff_A( 7, vi+V3i(0, 0, -1), 13 ) += -(0.478091443734*h_inv[2]);
	ctx.coeff_A( 7, vi+V3i(0, 0, 1), 13 ) += (0.478091443734*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.58533091904*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(2, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 7, vi+V3i(0, 0, 0), 7 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(2, 1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 7 ) += c;
	}
	// row=8 l=2 m=2 --------------------------
	ctx.coeff_A( 8, vi+V3i(-1, 0, 0), 15 ) += (0.462910049886*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(1, 0, 0), 15 ) += -(0.462910049886*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(-1, 0, 0), 3 ) += (0.4472135955*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(1, 0, 0), 3 ) += -(0.4472135955*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(-1, 0, 0), 13 ) += -(0.119522860933*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(1, 0, 0), 13 ) += (0.119522860933*h_inv[0]);
	ctx.coeff_A( 8, vi+V3i(0, -1, 0), 9 ) += (0.462910049886*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, 1, 0), 9 ) += -(0.462910049886*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, -1, 0), 1 ) += -(0.4472135955*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, 1, 0), 1 ) += (0.4472135955*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, -1, 0), 11 ) += (0.119522860933*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, 1, 0), 11 ) += -(0.119522860933*h_inv[1]);
	ctx.coeff_A( 8, vi+V3i(0, 0, -1), 14 ) += -(0.377964473009*h_inv[2]);
	ctx.coeff_A( 8, vi+V3i(0, 0, 1), 14 ) += (0.377964473009*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.58533091904*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(2, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 8, vi+V3i(0, 0, 0), 8 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(2, 2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 8 ) += c;
	}
	// row=9 l=3 m=-3 --------------------------
	ctx.coeff_A( 9, vi+V3i(0, -1, 0), 24 ) += -(0.471404520791*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(0, 1, 0), 24 ) += (0.471404520791*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(0, -1, 0), 8 ) += (0.462910049886*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(0, 1, 0), 8 ) += -(0.462910049886*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(0, -1, 0), 22 ) += -(0.0890870806375*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(0, 1, 0), 22 ) += (0.0890870806375*h_inv[1]);
	ctx.coeff_A( 9, vi+V3i(-1, 0, 0), 4 ) += (0.462910049886*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(1, 0, 0), 4 ) += -(0.462910049886*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(-1, 0, 0), 18 ) += -(0.0890870806375*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(1, 0, 0), 18 ) += (0.0890870806375*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(-1, 0, 0), 16 ) += (0.471404520791*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(1, 0, 0), 16 ) += -(0.471404520791*h_inv[0]);
	ctx.coeff_A( 9, vi+V3i(0, 0, -1), 17 ) += -(0.333333333333*h_inv[2]);
	ctx.coeff_A( 9, vi+V3i(0, 0, 1), 17 ) += (0.333333333333*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 9, vi+V3i(0, 0, 0), 9 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, -3, 0, 0, 0)[color_channel];
		ctx.coeff_b( 9 ) += c;
	}
	// row=10 l=3 m=-2 --------------------------
	ctx.coeff_A( 10, vi+V3i(0, -1, 0), 23 ) += -(0.408248290464*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(0, 1, 0), 23 ) += (0.408248290464*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(0, -1, 0), 7 ) += (0.377964473009*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(0, 1, 0), 7 ) += -(0.377964473009*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(0, -1, 0), 21 ) += -(0.154303349962*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(0, 1, 0), 21 ) += (0.154303349962*h_inv[1]);
	ctx.coeff_A( 10, vi+V3i(-1, 0, 0), 5 ) += (0.377964473009*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(1, 0, 0), 5 ) += -(0.377964473009*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(-1, 0, 0), 19 ) += -(0.154303349962*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(1, 0, 0), 19 ) += (0.154303349962*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(-1, 0, 0), 17 ) += (0.408248290464*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(1, 0, 0), 17 ) += -(0.408248290464*h_inv[0]);
	ctx.coeff_A( 10, vi+V3i(0, 0, -1), 4 ) += -(0.377964473009*h_inv[2]);
	ctx.coeff_A( 10, vi+V3i(0, 0, 1), 4 ) += (0.377964473009*h_inv[2]);
	ctx.coeff_A( 10, vi+V3i(0, 0, -1), 18 ) += -(0.436435780472*h_inv[2]);
	ctx.coeff_A( 10, vi+V3i(0, 0, 1), 18 ) += (0.436435780472*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 10, vi+V3i(0, 0, 0), 10 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, -2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 10 ) += c;
	}
	// row=11 l=3 m=-1 --------------------------
	ctx.coeff_A( 11, vi+V3i(0, -1, 0), 8 ) += (0.119522860933*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, 1, 0), 8 ) += -(0.119522860933*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, -1, 0), 22 ) += -(0.345032779671*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, 1, 0), 22 ) += (0.345032779671*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, -1, 0), 6 ) += (0.414039335605*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, 1, 0), 6 ) += -(0.414039335605*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, -1, 0), 20 ) += -(0.308606699924*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(0, 1, 0), 20 ) += (0.308606699924*h_inv[1]);
	ctx.coeff_A( 11, vi+V3i(-1, 0, 0), 4 ) += -(0.119522860933*h_inv[0]);
	ctx.coeff_A( 11, vi+V3i(1, 0, 0), 4 ) += (0.119522860933*h_inv[0]);
	ctx.coeff_A( 11, vi+V3i(-1, 0, 0), 18 ) += (0.345032779671*h_inv[0]);
	ctx.coeff_A( 11, vi+V3i(1, 0, 0), 18 ) += -(0.345032779671*h_inv[0]);
	ctx.coeff_A( 11, vi+V3i(0, 0, -1), 5 ) += -(0.478091443734*h_inv[2]);
	ctx.coeff_A( 11, vi+V3i(0, 0, 1), 5 ) += (0.478091443734*h_inv[2]);
	ctx.coeff_A( 11, vi+V3i(0, 0, -1), 19 ) += -(0.487950036474*h_inv[2]);
	ctx.coeff_A( 11, vi+V3i(0, 0, 1), 19 ) += (0.487950036474*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 11, vi+V3i(0, 0, 0), 11 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, -1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 11 ) += c;
	}
	// row=12 l=3 m=0 --------------------------
	ctx.coeff_A( 12, vi+V3i(-1, 0, 0), 7 ) += -(0.292770021885*h_inv[0]);
	ctx.coeff_A( 12, vi+V3i(1, 0, 0), 7 ) += (0.292770021885*h_inv[0]);
	ctx.coeff_A( 12, vi+V3i(-1, 0, 0), 21 ) += (0.398409536445*h_inv[0]);
	ctx.coeff_A( 12, vi+V3i(1, 0, 0), 21 ) += -(0.398409536445*h_inv[0]);
	ctx.coeff_A( 12, vi+V3i(0, -1, 0), 5 ) += -(0.292770021885*h_inv[1]);
	ctx.coeff_A( 12, vi+V3i(0, 1, 0), 5 ) += (0.292770021885*h_inv[1]);
	ctx.coeff_A( 12, vi+V3i(0, -1, 0), 19 ) += (0.398409536445*h_inv[1]);
	ctx.coeff_A( 12, vi+V3i(0, 1, 0), 19 ) += -(0.398409536445*h_inv[1]);
	ctx.coeff_A( 12, vi+V3i(0, 0, -1), 6 ) += -(0.507092552837*h_inv[2]);
	ctx.coeff_A( 12, vi+V3i(0, 0, 1), 6 ) += (0.507092552837*h_inv[2]);
	ctx.coeff_A( 12, vi+V3i(0, 0, -1), 20 ) += -(0.503952630679*h_inv[2]);
	ctx.coeff_A( 12, vi+V3i(0, 0, 1), 20 ) += (0.503952630679*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 12, vi+V3i(0, 0, 0), 12 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 12 ) += c;
	}
	// row=13 l=3 m=1 --------------------------
	ctx.coeff_A( 13, vi+V3i(-1, 0, 0), 8 ) += -(0.119522860933*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(1, 0, 0), 8 ) += (0.119522860933*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(-1, 0, 0), 22 ) += (0.345032779671*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(1, 0, 0), 22 ) += -(0.345032779671*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(-1, 0, 0), 6 ) += (0.414039335605*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(1, 0, 0), 6 ) += -(0.414039335605*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(-1, 0, 0), 20 ) += -(0.308606699924*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(1, 0, 0), 20 ) += (0.308606699924*h_inv[0]);
	ctx.coeff_A( 13, vi+V3i(0, -1, 0), 4 ) += -(0.119522860933*h_inv[1]);
	ctx.coeff_A( 13, vi+V3i(0, 1, 0), 4 ) += (0.119522860933*h_inv[1]);
	ctx.coeff_A( 13, vi+V3i(0, -1, 0), 18 ) += (0.345032779671*h_inv[1]);
	ctx.coeff_A( 13, vi+V3i(0, 1, 0), 18 ) += -(0.345032779671*h_inv[1]);
	ctx.coeff_A( 13, vi+V3i(0, 0, -1), 7 ) += -(0.478091443734*h_inv[2]);
	ctx.coeff_A( 13, vi+V3i(0, 0, 1), 7 ) += (0.478091443734*h_inv[2]);
	ctx.coeff_A( 13, vi+V3i(0, 0, -1), 21 ) += -(0.487950036474*h_inv[2]);
	ctx.coeff_A( 13, vi+V3i(0, 0, 1), 21 ) += (0.487950036474*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 13, vi+V3i(0, 0, 0), 13 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, 1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 13 ) += c;
	}
	// row=14 l=3 m=2 --------------------------
	ctx.coeff_A( 14, vi+V3i(-1, 0, 0), 23 ) += (0.408248290464*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(1, 0, 0), 23 ) += -(0.408248290464*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(-1, 0, 0), 7 ) += (0.377964473009*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(1, 0, 0), 7 ) += -(0.377964473009*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(-1, 0, 0), 21 ) += -(0.154303349962*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(1, 0, 0), 21 ) += (0.154303349962*h_inv[0]);
	ctx.coeff_A( 14, vi+V3i(0, -1, 0), 17 ) += (0.408248290464*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, 1, 0), 17 ) += -(0.408248290464*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, -1, 0), 5 ) += -(0.377964473009*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, 1, 0), 5 ) += (0.377964473009*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, -1, 0), 19 ) += (0.154303349962*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, 1, 0), 19 ) += -(0.154303349962*h_inv[1]);
	ctx.coeff_A( 14, vi+V3i(0, 0, -1), 8 ) += -(0.377964473009*h_inv[2]);
	ctx.coeff_A( 14, vi+V3i(0, 0, 1), 8 ) += (0.377964473009*h_inv[2]);
	ctx.coeff_A( 14, vi+V3i(0, 0, -1), 22 ) += -(0.436435780472*h_inv[2]);
	ctx.coeff_A( 14, vi+V3i(0, 0, 1), 22 ) += (0.436435780472*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 14, vi+V3i(0, 0, 0), 14 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, 2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 14 ) += c;
	}
	// row=15 l=3 m=3 --------------------------
	ctx.coeff_A( 15, vi+V3i(-1, 0, 0), 24 ) += (0.471404520791*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(1, 0, 0), 24 ) += -(0.471404520791*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(-1, 0, 0), 8 ) += (0.462910049886*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(1, 0, 0), 8 ) += -(0.462910049886*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(-1, 0, 0), 22 ) += -(0.0890870806375*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(1, 0, 0), 22 ) += (0.0890870806375*h_inv[0]);
	ctx.coeff_A( 15, vi+V3i(0, -1, 0), 16 ) += (0.471404520791*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, 1, 0), 16 ) += -(0.471404520791*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, -1, 0), 4 ) += -(0.462910049886*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, 1, 0), 4 ) += (0.462910049886*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, -1, 0), 18 ) += (0.0890870806375*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, 1, 0), 18 ) += -(0.0890870806375*h_inv[1]);
	ctx.coeff_A( 15, vi+V3i(0, 0, -1), 23 ) += -(0.333333333333*h_inv[2]);
	ctx.coeff_A( 15, vi+V3i(0, 0, 1), 23 ) += (0.333333333333*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.33984917138*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(3, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 15, vi+V3i(0, 0, 0), 15 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(3, 3, 0, 0, 0)[color_channel];
		ctx.coeff_b( 15 ) += c;
	}
	// row=16 l=4 m=-4 --------------------------
	ctx.coeff_A( 16, vi+V3i(0, -1, 0), 15 ) += (0.471404520791*h_inv[1]);
	ctx.coeff_A( 16, vi+V3i(0, 1, 0), 15 ) += -(0.471404520791*h_inv[1]);
	ctx.coeff_A( 16, vi+V3i(-1, 0, 0), 9 ) += (0.471404520791*h_inv[0]);
	ctx.coeff_A( 16, vi+V3i(1, 0, 0), 9 ) += -(0.471404520791*h_inv[0]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 16, vi+V3i(0, 0, 0), 16 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, -4, 0, 0, 0)[color_channel];
		ctx.coeff_b( 16 ) += c;
	}
	// row=17 l=4 m=-3 --------------------------
	ctx.coeff_A( 17, vi+V3i(0, -1, 0), 14 ) += (0.408248290464*h_inv[1]);
	ctx.coeff_A( 17, vi+V3i(0, 1, 0), 14 ) += -(0.408248290464*h_inv[1]);
	ctx.coeff_A( 17, vi+V3i(-1, 0, 0), 10 ) += (0.408248290464*h_inv[0]);
	ctx.coeff_A( 17, vi+V3i(1, 0, 0), 10 ) += -(0.408248290464*h_inv[0]);
	ctx.coeff_A( 17, vi+V3i(0, 0, -1), 9 ) += -(0.333333333333*h_inv[2]);
	ctx.coeff_A( 17, vi+V3i(0, 0, 1), 9 ) += (0.333333333333*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 17, vi+V3i(0, 0, 0), 17 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, -3, 0, 0, 0)[color_channel];
		ctx.coeff_b( 17 ) += c;
	}
	// row=18 l=4 m=-2 --------------------------
	ctx.coeff_A( 18, vi+V3i(0, -1, 0), 15 ) += (0.0890870806375*h_inv[1]);
	ctx.coeff_A( 18, vi+V3i(0, 1, 0), 15 ) += -(0.0890870806375*h_inv[1]);
	ctx.coeff_A( 18, vi+V3i(0, -1, 0), 13 ) += (0.345032779671*h_inv[1]);
	ctx.coeff_A( 18, vi+V3i(0, 1, 0), 13 ) += -(0.345032779671*h_inv[1]);
	ctx.coeff_A( 18, vi+V3i(-1, 0, 0), 9 ) += -(0.0890870806375*h_inv[0]);
	ctx.coeff_A( 18, vi+V3i(1, 0, 0), 9 ) += (0.0890870806375*h_inv[0]);
	ctx.coeff_A( 18, vi+V3i(-1, 0, 0), 11 ) += (0.345032779671*h_inv[0]);
	ctx.coeff_A( 18, vi+V3i(1, 0, 0), 11 ) += -(0.345032779671*h_inv[0]);
	ctx.coeff_A( 18, vi+V3i(0, 0, -1), 10 ) += -(0.436435780472*h_inv[2]);
	ctx.coeff_A( 18, vi+V3i(0, 0, 1), 10 ) += (0.436435780472*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 18, vi+V3i(0, 0, 0), 18 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, -2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 18 ) += c;
	}
	// row=19 l=4 m=-1 --------------------------
	ctx.coeff_A( 19, vi+V3i(0, -1, 0), 14 ) += (0.154303349962*h_inv[1]);
	ctx.coeff_A( 19, vi+V3i(0, 1, 0), 14 ) += -(0.154303349962*h_inv[1]);
	ctx.coeff_A( 19, vi+V3i(0, -1, 0), 12 ) += (0.398409536445*h_inv[1]);
	ctx.coeff_A( 19, vi+V3i(0, 1, 0), 12 ) += -(0.398409536445*h_inv[1]);
	ctx.coeff_A( 19, vi+V3i(-1, 0, 0), 10 ) += -(0.154303349962*h_inv[0]);
	ctx.coeff_A( 19, vi+V3i(1, 0, 0), 10 ) += (0.154303349962*h_inv[0]);
	ctx.coeff_A( 19, vi+V3i(0, 0, -1), 11 ) += -(0.487950036474*h_inv[2]);
	ctx.coeff_A( 19, vi+V3i(0, 0, 1), 11 ) += (0.487950036474*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 19, vi+V3i(0, 0, 0), 19 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, -1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 19 ) += c;
	}
	// row=20 l=4 m=0 --------------------------
	ctx.coeff_A( 20, vi+V3i(-1, 0, 0), 13 ) += -(0.308606699924*h_inv[0]);
	ctx.coeff_A( 20, vi+V3i(1, 0, 0), 13 ) += (0.308606699924*h_inv[0]);
	ctx.coeff_A( 20, vi+V3i(0, -1, 0), 11 ) += -(0.308606699924*h_inv[1]);
	ctx.coeff_A( 20, vi+V3i(0, 1, 0), 11 ) += (0.308606699924*h_inv[1]);
	ctx.coeff_A( 20, vi+V3i(0, 0, -1), 12 ) += -(0.503952630679*h_inv[2]);
	ctx.coeff_A( 20, vi+V3i(0, 0, 1), 12 ) += (0.503952630679*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 20, vi+V3i(0, 0, 0), 20 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 20 ) += c;
	}
	// row=21 l=4 m=1 --------------------------
	ctx.coeff_A( 21, vi+V3i(-1, 0, 0), 14 ) += -(0.154303349962*h_inv[0]);
	ctx.coeff_A( 21, vi+V3i(1, 0, 0), 14 ) += (0.154303349962*h_inv[0]);
	ctx.coeff_A( 21, vi+V3i(-1, 0, 0), 12 ) += (0.398409536445*h_inv[0]);
	ctx.coeff_A( 21, vi+V3i(1, 0, 0), 12 ) += -(0.398409536445*h_inv[0]);
	ctx.coeff_A( 21, vi+V3i(0, -1, 0), 10 ) += -(0.154303349962*h_inv[1]);
	ctx.coeff_A( 21, vi+V3i(0, 1, 0), 10 ) += (0.154303349962*h_inv[1]);
	ctx.coeff_A( 21, vi+V3i(0, 0, -1), 13 ) += -(0.487950036474*h_inv[2]);
	ctx.coeff_A( 21, vi+V3i(0, 0, 1), 13 ) += (0.487950036474*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 21, vi+V3i(0, 0, 0), 21 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, 1, 0, 0, 0)[color_channel];
		ctx.coeff_b( 21 ) += c;
	}
	// row=22 l=4 m=2 --------------------------
	ctx.coeff_A( 22, vi+V3i(-1, 0, 0), 15 ) += -(0.0890870806375*h_inv[0]);
	ctx.coeff_A( 22, vi+V3i(1, 0, 0), 15 ) += (0.0890870806375*h_inv[0]);
	ctx.coeff_A( 22, vi+V3i(-1, 0, 0), 13 ) += (0.345032779671*h_inv[0]);
	ctx.coeff_A( 22, vi+V3i(1, 0, 0), 13 ) += -(0.345032779671*h_inv[0]);
	ctx.coeff_A( 22, vi+V3i(0, -1, 0), 9 ) += -(0.0890870806375*h_inv[1]);
	ctx.coeff_A( 22, vi+V3i(0, 1, 0), 9 ) += (0.0890870806375*h_inv[1]);
	ctx.coeff_A( 22, vi+V3i(0, -1, 0), 11 ) += -(0.345032779671*h_inv[1]);
	ctx.coeff_A( 22, vi+V3i(0, 1, 0), 11 ) += (0.345032779671*h_inv[1]);
	ctx.coeff_A( 22, vi+V3i(0, 0, -1), 14 ) += -(0.436435780472*h_inv[2]);
	ctx.coeff_A( 22, vi+V3i(0, 0, 1), 14 ) += (0.436435780472*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 22, vi+V3i(0, 0, 0), 22 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, 2, 0, 0, 0)[color_channel];
		ctx.coeff_b( 22 ) += c;
	}
	// row=23 l=4 m=3 --------------------------
	ctx.coeff_A( 23, vi+V3i(-1, 0, 0), 14 ) += (0.408248290464*h_inv[0]);
	ctx.coeff_A( 23, vi+V3i(1, 0, 0), 14 ) += -(0.408248290464*h_inv[0]);
	ctx.coeff_A( 23, vi+V3i(0, -1, 0), 10 ) += -(0.408248290464*h_inv[1]);
	ctx.coeff_A( 23, vi+V3i(0, 1, 0), 10 ) += (0.408248290464*h_inv[1]);
	ctx.coeff_A( 23, vi+V3i(0, 0, -1), 15 ) += -(0.333333333333*h_inv[2]);
	ctx.coeff_A( 23, vi+V3i(0, 0, 1), 15 ) += (0.333333333333*h_inv[2]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 23, vi+V3i(0, 0, 0), 23 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, 3, 0, 0, 0)[color_channel];
		ctx.coeff_b( 23 ) += c;
	}
	// row=24 l=4 m=4 --------------------------
	ctx.coeff_A( 24, vi+V3i(-1, 0, 0), 15 ) += (0.471404520791*h_inv[0]);
	ctx.coeff_A( 24, vi+V3i(1, 0, 0), 15 ) += -(0.471404520791*h_inv[0]);
	ctx.coeff_A( 24, vi+V3i(0, -1, 0), 9 ) += -(0.471404520791*h_inv[1]);
	ctx.coeff_A( 24, vi+V3i(0, 1, 0), 9 ) += (0.471404520791*h_inv[1]);
	{
		double c = 0.0;
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(1.1816359006*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(4, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 24, vi+V3i(0, 0, 0), 24 ) += c;
	}
	{
		double c = 0.0;
		c+=ctx.evalEmission(4, 4, 0, 0, 0)[color_channel];
		ctx.coeff_b( 24 ) += c;
	}
}
V3i stencil_p4_3d_cg_get_offset(int coeff)
{
	switch(coeff)
	{
		case 0:return V3i(1, 1, 1);break;
		case 1:return V3i(1, 1, 1);break;
		case 2:return V3i(1, 1, 1);break;
		case 3:return V3i(1, 1, 1);break;
		case 4:return V3i(1, 1, 1);break;
		case 5:return V3i(1, 1, 1);break;
		case 6:return V3i(1, 1, 1);break;
		case 7:return V3i(1, 1, 1);break;
		case 8:return V3i(1, 1, 1);break;
		case 9:return V3i(1, 1, 1);break;
		case 10:return V3i(1, 1, 1);break;
		case 11:return V3i(1, 1, 1);break;
		case 12:return V3i(1, 1, 1);break;
		case 13:return V3i(1, 1, 1);break;
		case 14:return V3i(1, 1, 1);break;
		case 15:return V3i(1, 1, 1);break;
		case 16:return V3i(1, 1, 1);break;
		case 17:return V3i(1, 1, 1);break;
		case 18:return V3i(1, 1, 1);break;
		case 19:return V3i(1, 1, 1);break;
		case 20:return V3i(1, 1, 1);break;
		case 21:return V3i(1, 1, 1);break;
		case 22:return V3i(1, 1, 1);break;
		case 23:return V3i(1, 1, 1);break;
		case 24:return V3i(1, 1, 1);break;
		default:throw std::runtime_error("unexpected coefficient index");break;
	};
}
REGISTER_STENCIL(stencil_p4_3d_cg, 4, 25, 1)
