/*
// This file was generated by stencil2.py

#include <PNSystem.h>

void stencil2_fopn_p1_sg(PNSystem::Stencil::Context& ctx)
{
	V3i vi = ctx.getVoxelCoord();
	V3d vd = vi.cast<double>();
	const Domain& domain = ctx.getDomain();
	const PNVolume& problem = ctx.getProblem();
	V3d h_inv( 1.0/(1*domain.getVoxelSize()[0]), 1.0/(1*domain.getVoxelSize()[1]), 1.0/(1*domain.getVoxelSize()[2]) );
	int color_channel = 0;

	// row=0 --------------------------
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(0.57735026919*h_inv[0]);
		ctx.coeff_A( 0, vi+V3i(0, 0, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.57735026919*h_inv[0]);
		ctx.coeff_A( 0, vi+V3i(1, 0, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(0.57735026919*h_inv[1]);
		ctx.coeff_A( 0, vi+V3i(0, 0, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.57735026919*h_inv[1]);
		ctx.coeff_A( 0, vi+V3i(0, 1, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=ctx.evalExtinction(0, 0, 0)[color_channel];
		c+=-(3.54490770181*ctx.evalScattering(0, 0, 0)[color_channel]*ctx.evalPhase(0, 0, 0, 0, 0)[color_channel]);
		ctx.coeff_A( 0, vi+V3i(0, 0, 0), 0 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=ctx.evalEmission(0, 0, 0, 0, 0)[color_channel];
		ctx.coeff_b( 0 ) += c.real();
	}
	// row=1 --------------------------
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(0.57735026919*h_inv[1]);
		ctx.coeff_A( 1, vi+V3i(0, -1, 0), 0 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.57735026919*h_inv[1]);
		ctx.coeff_A( 1, vi+V3i(0, 0, 0), 0 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.25*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(0, 0, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(0, -1, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(0, 0, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(1, -1, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, -1, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 1, vi+V3i(1, 0, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.25*ctx.evalEmission(1, -1, 0, -1, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, -1, 0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, 1, 0, -1, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, 1, 0, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, -1, 0, -1, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, -1, 0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, 1, 0, -1, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, 1, 0, 0, 0)[color_channel]);
		ctx.coeff_b( 1 ) += c.real();
	}
	// row=2 --------------------------
	{
		std::complex<double> c(0.0, 0.0);
		c+=-(0.57735026919*h_inv[0]);
		ctx.coeff_A( 2, vi+V3i(-1, 0, 0), 0 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.57735026919*h_inv[0]);
		ctx.coeff_A( 2, vi+V3i(0, 0, 0), 0 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(-1, 0, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(-1, 1, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(0, 0, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.062499999999999986)*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.06395791924665552)*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(0, 1, 0), 1 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(0.25*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(-1, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalExtinction(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(-1, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, -1, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		c+=-(0.255831676987*ctx.evalPhase(1, 0, 0, 0, 0)[color_channel]*ctx.evalScattering(0, 0, 0)[color_channel]);
		ctx.coeff_A( 2, vi+V3i(0, 0, 0), 2 ) += c.real();
	}
	{
		std::complex<double> c(0.0, 0.0);
		c+=(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, -1, -1, 0, 0)[color_channel]);
		c+=(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, -1, 0, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, 1, -1, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, 1, 0, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, -1, -1, 0, 0)[color_channel]);
		c+=-(std::complex<double>(0.0, 0.24999999999999994)*ctx.evalEmission(1, -1, 0, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, 1, -1, 0, 0)[color_channel]);
		c+=(0.25*ctx.evalEmission(1, 1, 0, 0, 0)[color_channel]);
		ctx.coeff_b( 2 ) += c.real();
	}
}
V3i stencil2_fopn_p1_sg_get_offset(int coeff)
{
	switch(coeff)
	{
		case 0:return V3i(1, 1, 1);break;
		case 1:return V3i(1, 0, 1);break;
		case 2:return V3i(0, 1, 1);break;
		default:throw std::runtime_error("unexpected coefficient index");break;
	};
}
REGISTER_STENCIL(stencil2_fopn_p1_sg, 1, 3, 1)

*/
